=== bere99/Sar-music-app/xml/dtd/user.dtd
<!DOCTYPE user
[
<!ELEMENT user (userInfo, playlists)>
<!ELEMENT userInfo (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT playlists (playlist)*>
<!ATTLIST playlist name #PCDATA >
<!ELEMENT playlist (songID)*>
<!ELEMENT songID (#PCDATA)>
]>

=== bere99/Sar-music-app/users/JJJosean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "user.dtd">
<user>
    <userInfo>
        <name>JJJosean</name>
    </userInfo>
    <playlists>
        <playlist name="Mi playlist">
            <songID>1</songID>
            <songID>2</songID>
        </playlist>
        <playlist name="Picadores de codigo">
            <songID>2</songID>
            <songID>1</songID>
        </playlist>
    </playlists>
</user>
